package com.ysj.myfirstopendemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ysj.myfirstopendemo.Artical;

import com.ysj.myfirstopendemo.ArticalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articalDaoConfig;

    private final ArticalDao articalDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articalDaoConfig = daoConfigMap.get(ArticalDao.class).clone();
        articalDaoConfig.initIdentityScope(type);

        articalDao = new ArticalDao(articalDaoConfig, this);

        registerDao(Artical.class, articalDao);
    }
    
    public void clear() {
        articalDaoConfig.clearIdentityScope();
    }

    public ArticalDao getArticalDao() {
        return articalDao;
    }

}
